import { CategoryNode } from './types';

const CATEGORY_PATHS: string[] = [
  'Bulding Materials > Boards and Sheeting > Boards and Shelving',
  'Bulding Materials > Boards and Sheeting > Skirtings',
  'Bulding Materials > Building Tools > Ladders',
  'Bulding Materials > Building Tools > Trestles',
  'Bulding Materials > Ceiling > Ceiling Accessories',
  'Bulding Materials > Ceiling > Cornices',
  'Bulding Materials > Roofing > Plastic Sheeting',
  'Bulding Materials > Roofing > Roof Insulation',
  'Bulding Materials > Roofing > Roof Sheeting Accessories',
  'Decore Furniture and Home Living > Bathroom Accessories > Bathroom Wall Fittings',
  'Decore Furniture and Home Living > Bathroom Accessories > Laundry Baskets',
  'Decore Furniture and Home Living > Blinds > Off-the-Shelf Blinds',
  'Decore Furniture and Home Living > Cleaning > Bathroom Cleaning',
  'Decore Furniture and Home Living > Cleaning > Bin Liners and Bags',
  'Decore Furniture and Home Living > Cleaning > Brooms and Brushwares',
  'Decore Furniture and Home Living > Cleaning > Buckets and Basins',
  'Decore Furniture and Home Living > Cleaning > Domestic Uniforms and Gloves',
  'Decore Furniture and Home Living > Cleaning > Drain Cleaning',
  'Decore Furniture and Home Living > Cleaning > Floor Cleaning',
  'Decore Furniture and Home Living > Cleaning > Home Fresheners',
  'Decore Furniture and Home Living > Cleaning > Household Bins',
  'Decore Furniture and Home Living > Cleaning > Kitchen Cleaning',
  'Decore Furniture and Home Living > Cleaning > Mops',
  'Decore Furniture and Home Living > Cleaning > Multipurpose Cleaning',
  'Decore Furniture and Home Living > Cleaning > Pest Control',
  'Decore Furniture and Home Living > Cleaning > Scrubs Brushes, Sponges and Cloths',
  'Decore Furniture and Home Living > Curtains and Curtain Accessories > Curtain Rails',
  'Decore Furniture and Home Living > Curtains and Curtain Accessories > Curtain Rails Accessories',
  'Decore Furniture and Home Living > Kitchen Accessories > Handles Hinges and Cabinet Hardware',
  'Decore Furniture and Home Living > Laundry and Washing Lines > Hangers',
  'Decore Furniture and Home Living > Laundry and Washing Lines > Laundry Baskets',
  'Decore Furniture and Home Living > Laundry and Washing Lines > Rotary Washing Lines',
  'Decore Furniture and Home Living > Laundry and Washing Lines > Wall Mounted Washing Lines',
  'Decore Furniture and Home Living > Laundry and Washing Lines > Washing Line Replacement Lines and Pegs',
  'Decore Furniture and Home Living > Shelving > Laminating Shelving',
  'Decore Furniture and Home Living > Storage Containers > Plastic Storage',
  'Doors and Windows > Curtains and Curtain Accessories > Curtain Rails',
  'Doors and Windows > Curtains and Curtain Accessories > Rail Accessories',
  'Doors and Windows > Curtains and Curtain Accessories > Steel Curtain Rods',
  'Doors and Windows > Curtains and Curtain Accessories > Wood Curtain Rods',
  'Doors and Windows > Door Accessories > Castors',
  'Doors and Windows > Door Accessories > Door Furniture',
  'Doors and Windows > Door Accessories > Door Handles',
  'Doors and Windows > Door Accessories > Door Hinges',
  'Doors and Windows > Door Accessories > Door Locks',
  'Doors and Windows > Doors > Door Frames',
  'Doors and Windows > Doors > Entrance Doors',
  'Doors and Windows > Doors > Folding Doors',
  'Doors and Windows > Doors > Garage Doors',
  'Doors and Windows > Doors > Internal Doors',
  'Doors and Windows > Doors > Service Doors',
  'Doors and Windows > Doors > Sliding Doors',
  'Doors and Windows > Window Accessories > Blinds',
  'Doors and Windows > Window Accessories > Curtain Accessories',
  'Doors and Windows > Window Accessories > Curtains',
  'Doors and Windows > Window Accessories > Glass and Putty',
  'Doors and Windows > Window Accessories > Ironmongery Accessories',
  'Doors and Windows > Window Accessories > Window Furniture',
  'Doors and Windows > Windows > Aluminium Windows',
  'Doors and Windows > Windows > Steel Windows',
  'Fasteners and Adhesives > Adhesives > Adhesive Accessories',
  'Fasteners and Adhesives > Adhesives > Adhesive Putty',
  'Fasteners and Adhesives > Adhesives > Carpet Adhesive',
  'Fasteners and Adhesives > Adhesives > Chemical Anchors',
  'Fasteners and Adhesives > Adhesives > Contact Adhesives',
  'Fasteners and Adhesives > Adhesives > Cornice Adhesive',
  'Fasteners and Adhesives > Adhesives > Epoxy',
  'Fasteners and Adhesives > Adhesives > Epoxy Paint',
  'Fasteners and Adhesives > Adhesives > General Purpose Adhesive',
  'Fasteners and Adhesives > Adhesives > PVC Weld',
  'Fasteners and Adhesives > Adhesives > Speciality Adhesive',
  'Fasteners and Adhesives > Adhesives > Super Glue',
  'Fasteners and Adhesives > Adhesives > Wallpaper Adhesives',
  'Fasteners and Adhesives > Adhesives > Wood Adhesive',
  'Fasteners and Adhesives > Fasteners > Bubble Wrap',
  'Fasteners and Adhesives > Fasteners > Chains',
  'Fasteners and Adhesives > Fasteners > Fasteners and Springs',
  'Fasteners and Adhesives > Fasteners > Hooks and Ties',
  'Fasteners and Adhesives > Fasteners > Plastic Tubing',
  'Fasteners and Adhesives > Fasteners > PVC Wire',
  'Fasteners and Adhesives > Fasteners > Rigging',
  'Fasteners and Adhesives > Fasteners > Rope',
  'Fasteners and Adhesives > Fasteners > Twine and Cords',
  'Fasteners and Adhesives > Nails > Expansion Bolts',
  'Fasteners and Adhesives > Nails > Nail-in Anchors',
  'Fasteners and Adhesives > Nails > Nails',
  'Fasteners and Adhesives > Nuts and Bolts > Bolts',
  'Fasteners and Adhesives > Nuts and Bolts > Nuts',
  'Fasteners and Adhesives > Nuts and Bolts > Nuts and Bolt Bulk',
  'Fasteners and Adhesives > Screws > Chipboard Screws',
  'Fasteners and Adhesives > Screws > Coach Screws and Plugs',
  'Fasteners and Adhesives > Screws > Cut Screws',
  'Fasteners and Adhesives > Screws > Drywall and Woodscrews',
  'Fasteners and Adhesives > Screws > Roof and Metal Screws',
  'Fasteners and Adhesives > Screws > Washers',
  'Fasteners and Adhesives > Silicone > Caulking Guns',
  'Fasteners and Adhesives > Silicone > Foams',
  'Fasteners and Adhesives > Silicone > Gasket',
  'Fasteners and Adhesives > Silicone > Paintable Acrylic',
  'Fasteners and Adhesives > Silicone > Sealant Adhesive',
  'Fasteners and Adhesives > Silicone > Sealant Sanitary',
  'Fasteners and Adhesives > Silicone > Sealant Speciality',
  'Fasteners and Adhesives > Silicone > Sealant Wood',
  'Fasteners and Adhesives > Silicone > Silicone Sealant',
  'Fasteners and Adhesives > Tape and Seal Strips > Double sided Tapes',
  'Fasteners and Adhesives > Tape and Seal Strips > Duct Tape',
  'Fasteners and Adhesives > Tape and Seal Strips > General Purpose Tapes',
  'Fasteners and Adhesives > Tape and Seal Strips > Masking Tapes',
  'Fasteners and Adhesives > Tape and Seal Strips > Seal Strip',
  'Fasteners and Adhesives > Tape and Seal Strips > Specialty Tapes',
  'Fasteners and Adhesives > Tape and Seal Strips > Waterproofing Tapes',
  'Load Shedding > Emergency Lighting > Rechargeable Lights',
  'Load Shedding > Emergency Lighting > Solar Lights',
  'Load Shedding > Gas Cooking > Gas Cylinders',
  'Load Shedding > Gas Cooking > Gas Stoves',
  'Outdoor Garden and Patio > Gardening Tools > Chainsaws',
  'Outdoor Garden and Patio > Gardening Tools > Garden Blowers and Vacuums',
  'Outdoor Garden and Patio > Gardening Tools > Garden Cordless Power Tools',
  'Outdoor Garden and Patio > Gardening Tools > Garden Hand Tools',
  'Outdoor Garden and Patio > Gardening Tools > Garden Spray Bottles',
  'Outdoor Garden and Patio > Gardening Tools > Lawnmower Accessories',
  'Outdoor Garden and Patio > Gardening Tools > Tillers and Earth Augers',
  'Outdoor Garden and Patio > Gardening Tools > Trimmer Accessories',
  'Outdoor Garden and Patio > Gardening Tools > Trimmers',
  'Outdoor Garden and Patio > Outdoor Accessories > Laundry and Washing Lines',
  'Outdoor Garden and Patio > Outdoor Accessories > Refuse Bins',
  'Outdoor Garden and Patio > Patio Furniture > Outdoor Umbrellas and Pavilions',
  'Outdoor Garden and Patio > Patio Furniture > Plastic Furniture',
  'Outdoor Garden and Patio > Patio Furniture > Shade Cloths and Accessories',
  'Outdoor Garden and Patio > Plants and Artificial Grass > Artificial Grass',
  'Outdoor Garden and Patio > Plants and Artificial Grass > Seeds',
  'Outdoor Garden and Patio > Water and Irrigation > Hose Fittings and Connectors',
  'Outdoor Garden and Patio > Water and Irrigation > Hose Holders',
  'Outdoor Garden and Patio > Water and Irrigation > Hose Pipes',
  'Outdoor Garden and Patio > Water and Irrigation > Hose Sprinklers and Sprayers',
  'Outdoor Garden and Patio > Water and Irrigation > Watering Cans',
  'Outdoor Garden and Patio > Water Tanks and Filtration > Water Tank Accessories and Chemicals',
  'Outdoor Garden and Patio > Water Tanks and Filtration > Water Tank Pumps',
  'Paint > Enamel Paint > Enamel Eggshell Paint',
  'Paint > Enamel Paint > Enamel Gloss Paint',
  'Paint > Enamel Paint > Enamel Metal Paint',
  'Paint > Enamel Paint > Enamel Quick Dry Paint',
  'Paint > Enamel Paint > Enamel Sheen Paint',
  'Paint > Enamel Paint > Enamel Water-Based Paint',
  'Paint > Paint Accessories > Cloths Sponges and Steel Wool',
  'Paint > Paint Accessories > Drop Sheets',
  'Paint > Paint Accessories > Mutton Cloth and Rugs',
  'Paint > Paint Accessories > Paint Brushes and Sets',
  'Paint > Paint Accessories > Paint Roller Extension Pole',
  'Paint > Paint Accessories > Paint Rollers',
  'Paint > Paint Accessories > Sand Paper Rolls and Blocks',
  'Paint > Paint Accessories > Scrapers',
  'Paint > Paint Accessories > Solvents',
  'Paint > Paint Accessories > Waterpaper',
  'Paint > Preparation and Finishing > Additives',
  'Paint > Preparation and Finishing > Bonding Agents',
  'Paint > Preparation and Finishing > Lacquer Thinners and Mineral Turpentine',
  'Paint > Preparation and Finishing > Oxides',
  'Paint > Preparation and Finishing > Paint Stripper',
  'Paint > Preparation and Finishing > Rust Agents',
  'Paint > Preparation and Finishing > Sealers',
  'Paint > Preparation and Finishing > Skimmer Plaster',
  'Paint > Preparation and Finishing > Sugar Soap',
  'Paint > Primer and Undercoat > Metal Primer',
  'Paint > Primer and Undercoat > Plaster and Solvent Primer',
  'Paint > Primer and Undercoat > Undercoats',
  'Paint > Primer and Undercoat > Water-Based Primer',
  'Paint > Primer and Undercoat > Wood Primer',
  'Paint > PVA Paint > Contractors Paint',
  'Paint > PVA Paint > Fine Texture',
  'Paint > PVA Paint > Matte Finish',
  'Paint > PVA Paint > Sheen Finish',
  'Paint > PVA Paint > Smooth Finish',
  'Paint > Shop by Application > Bathroom and Kitchen',
  'Paint > Shop by Application > Ceiling Paint',
  'Paint > Shop by Application > Floor Stoep and Paving Paint',
  'Paint > Shop by Application > Metal Paint',
  'Paint > Shop by Application > Road Marking Paint',
  'Paint > Shop by Application > Waterproofing Paint',
  'Paint > Spray Paint > Gloss Spray Paint',
  'Paint > Spray Paint > Hammered Spray Paint',
  'Paint > Spray Paint > Metal Spray Paint',
  'Paint > Spray Paint > Speciality Spray Paint',
  'Paint > Spray Paint > Spray Paint Primer',
  'Paint > Waterproofing > Damp',
  'Paint > Waterproofing > Pond Waterproofing',
  'Paint > Waterproofing > Pure Acrylic Waterproofing',
  'Paint > Waterproofing > Waterproofing Additives',
  'Paint > Waterproofing > Waterproofing Bitumen',
  'Paint > Waterproofing > Waterproofing Fibre',
  'Paint > Waterproofing > Waterproofing Kits',
  'Paint > Waterproofing > Waterproofing Membranes',
  'Paint > Waterproofing > Waterproofing Paint',
  'Paint > Waterproofing > Waterproofing Tapes',
  'Paint > Wood Finish > Carbolineum',
  'Paint > Wood Finish > Creosote',
  'Paint > Wood Finish > Deck Coating',
  'Paint > Wood Finish > Gloss Wood Varnish',
  'Paint > Wood Finish > Linseed Oil',
  'Paint > Wood Finish > Waksol',
  'Paint > Wood Finish > Wood Preservatives',
  'Paint > Wood Finish > Wood Sealers',
  'Plumbing Bathroom and Kitchen > Basins and Cabinets > Basins and Cabinets Sets',
  'Plumbing Bathroom and Kitchen > Basins and Cabinets > Basins and Pedestals',
  'Plumbing Bathroom and Kitchen > Basins and Cabinets > Bathroom Cabinets',
  'Plumbing Bathroom and Kitchen > Basins and Cabinets > Mirror Cabinets',
  'Plumbing Bathroom and Kitchen > Baths and Bath Spouts > Bath Spouts',
  'Plumbing Bathroom and Kitchen > Baths and Bath Spouts > Drop in Baths',
  'Plumbing Bathroom and Kitchen > Geysers and Water Heaters > Gas Geysers and Accessories',
  'Plumbing Bathroom and Kitchen > Geysers and Water Heaters > Geyser Accessories',
  'Plumbing Bathroom and Kitchen > Geysers and Water Heaters > Geysers',
  'Plumbing Bathroom and Kitchen > Geysers and Water Heaters > Instant Water Heaters',
  'Plumbing Bathroom and Kitchen > Geysers and Water Heaters > Solar Geysers',
  'Plumbing Bathroom and Kitchen > Geysers and Water Heaters > Solar Geysers Accessories',
  'Plumbing Bathroom and Kitchen > Gutters > Rainwater Goods Accessories',
  'Plumbing Bathroom and Kitchen > Kitchen > Furniture Legs',
  'Plumbing Bathroom and Kitchen > Kitchen > Kitchen Accessories',
  'Plumbing Bathroom and Kitchen > Kitchen > Kitchen Cupboards',
  'Plumbing Bathroom and Kitchen > Kitchen > Kitchen Sinks and Accessories',
  'Plumbing Bathroom and Kitchen > Kitchen > Kitchen Taps',
  'Plumbing Bathroom and Kitchen > Pipes and Fittings > Compression Pipe and Fittings',
  'Plumbing Bathroom and Kitchen > Pipes and Fittings > Copper Pipes and Fittings',
  'Plumbing Bathroom and Kitchen > Pipes and Fittings > Galvanised Pipe and Fittings',
  'Plumbing Bathroom and Kitchen > Pipes and Fittings > HDPE Pipes and Fittings',
  'Plumbing Bathroom and Kitchen > Pipes and Fittings > Plastic Pipes and Fittings',
  'Plumbing Bathroom and Kitchen > Pipes and Fittings > Polycop Pipesand Fittings',
  'Plumbing Bathroom and Kitchen > Pipes and Fittings > PVC Pipes and Fittings',
  'Plumbing Bathroom and Kitchen > Plumbing Accessories > Pluming Accessories.',
  'Plumbing Bathroom and Kitchen > Plumbing Accessories > Washing Machine Accessories',
  'Plumbing Bathroom and Kitchen > Showers and Accessories > Shower Curtains',
  'Plumbing Bathroom and Kitchen > Showers and Accessories > Shower Door Spares',
  'Plumbing Bathroom and Kitchen > Showers and Accessories > Shower Doors',
  'Plumbing Bathroom and Kitchen > Showers and Accessories > Shower Roseand Hand Showers',
  'Plumbing Bathroom and Kitchen > Showers and Accessories > Shower Spares and Hoses',
  'Plumbing Bathroom and Kitchen > Taps > Taps Accessories',
  'Plumbing Bathroom and Kitchen > Taps > Taps and Mixers',
  'Plumbing Bathroom and Kitchen > Toilets and Accessories > Cisterns and Urinals',
  'Plumbing Bathroom and Kitchen > Toilets and Accessories > Toilet Flush Plates',
  'Plumbing Bathroom and Kitchen > Toilets and Accessories > Toilet Seat Accessories',
  'Plumbing Bathroom and Kitchen > Toilets and Accessories > Toilet Seats',
  'Plumbing Bathroom and Kitchen > Toilets and Accessories > Toilet Spares',
  'Plumbing Bathroom and Kitchen > Toilets and Accessories > Toilet Valves',
  'Plumbing Bathroom and Kitchen > Toilets and Accessories > Toilets',
  'Plumbing Bathroom and Kitchen > Waste and Traps > Cast Iron Drain and Accessories',
  'Plumbing Bathroom and Kitchen > Waste and Traps > Drains',
  'Plumbing Bathroom and Kitchen > Waste and Traps > Traps',
  'Plumbing Bathroom and Kitchen > Waste and Traps > Waste',
  'Plumbing Bathroom and Kitchen > Waste and Traps > Waste Spares',
  'Safety and Protective Wear > Footwear > Gumboots',
  'Safety and Protective Wear > Footwear > Safety Boots',
  'Safety and Protective Wear > Footwear > Safety Shoes',
  'Safety and Protective Wear > Overalls > Conti Suits',
  'Safety and Protective Wear > Overalls > Flame and Acid Conti Suits',
  'Safety and Protective Wear > Overalls > Single Conti Suits',
  'Safety and Protective Wear > Safety Equipment > Dust Masks',
  'Safety and Protective Wear > Safety Equipment > Ear Protection',
  'Safety and Protective Wear > Safety Equipment > Eye Protection',
  'Safety and Protective Wear > Safety Equipment > Gloves',
  'Safety and Protective Wear > Safety Equipment > Hardhats',
  'Safety and Protective Wear > Safety Equipment > Harnesses',
  'Safety and Protective Wear > Safety Equipment > Rain Suits',
  'Safety and Protective Wear > Safety Equipment > Reflector Vests and Jackets',
  'Safety and Protective Wear > Safety Equipment > Respiratory',
  'Safety and Protective Wear > Site Safety > Cones',
  'Safety and Protective Wear > Site Safety > Danger Tape and Netting',
  'Safety and Protective Wear > Site Safety > Reflector Vest and Jackets',
  'Security and Smart Home > Home Security > Keys',
  'Security and Smart Home > Home Security > Padlocks',
  'Security and Smart Home > Home Security > Safes',
  'Security and Smart Home > Home Security > Security Doors',
  'Security and Smart Home > Home Security > Security Locks',
  'Tiles and Flooring > Flooring > Artificial Grass',
  'Tiles and Flooring > Flooring > Laminate Flooring',
  'Tiles and Flooring > Flooring > Vinyl Flooring',
  'Tiles and Flooring > Flooring Accessories > Laminate Flooring Trims',
  'Tiles and Flooring > Flooring Accessories > Skirting',
  'Tiles and Flooring > Flooring Accessories > Wood Finish',
  'Tiles and Flooring > Tiles > Mosaic Tiles',
  'Tiles and Flooring > Tiles > Natural Stone Tiles',
  'Tiles and Flooring > Tiles Accessories > Tile Grouts',
  'Tiles and Flooring > Tiles Accessories > Tile Tools',
  'Tiles and Flooring > Tiles Accessories > Tile Trims',
  'Tiles and Flooring > Tiles Accessories > Tiles Additives and Cleaners',
  'Tiles and Flooring > Tiles Accessories > Wall Borders and Cladding',
  'Tools and Machinery > Automotive > Automotive Cleaning',
  'Tools and Machinery > Automotive > Automotive Lubricants and Additives',
  'Tools and Machinery > Automotive > Automotive Straps',
  'Tools and Machinery > Drill Accessories > Chucks and Keys',
  'Tools and Machinery > Drill Accessories > Drill Bits Sets',
  'Tools and Machinery > Drill Accessories > Masonry Drill Bits',
  'Tools and Machinery > Drill Accessories > Screwdriver Bits',
  'Tools and Machinery > Drill Accessories > SDS Chisels',
  'Tools and Machinery > Drill Accessories > SDS Drill Bits',
  'Tools and Machinery > Drill Accessories > Specialised Drill Bits',
  'Tools and Machinery > Drill Accessories > Steel Drill Bits',
  'Tools and Machinery > Drill Accessories > Universal Drill Bits',
  'Tools and Machinery > Drill Accessories > Wood Drill Bits',
  'Tools and Machinery > Electrical Hand Tools > Glue Guns and Glue Sticks',
  'Tools and Machinery > Electrical Hand Tools > Staple Guns and Staples',
  'Tools and Machinery > Grinding Accessories > Abrasive Cutting Disc',
  'Tools and Machinery > Grinding Accessories > Abrasive Flap Discs',
  'Tools and Machinery > Grinding Accessories > Abrasive Grinding Disc',
  'Tools and Machinery > Grinding Accessories > Diamond Disc',
  'Tools and Machinery > Grinding Accessories > Grinding Wheels and Accessories',
  'Tools and Machinery > Grinding Accessories > Wire Cup Brushes',
  'Tools and Machinery > Hand Tools > Bolt Cutters and Tin Snip',
  'Tools and Machinery > Hand Tools > Chisels and Crowbar',
  'Tools and Machinery > Hand Tools > Clamps and Vices',
  'Tools and Machinery > Hand Tools > Files and Rasps',
  'Tools and Machinery > Hand Tools > Hammers and Mallets',
  'Tools and Machinery > Hand Tools > Hand Planers',
  'Tools and Machinery > Hand Tools > Knives Blades and Scrapers',
  'Tools and Machinery > Hand Tools > Levels and Accessories',
  'Tools and Machinery > Hand Tools > Mechanic Tools',
  'Tools and Machinery > Hand Tools > Oil Stones and Sharpening Tools',
  'Tools and Machinery > Hand Tools > Pliers',
  'Tools and Machinery > Hand Tools > Saws and Accessories',
  'Tools and Machinery > Hand Tools > Screwdrivers and Allen Keys',
  'Tools and Machinery > Hand Tools > Spanners and Sockets',
  'Tools and Machinery > Hand Tools > Stampers and Punches',
  'Tools and Machinery > Hand Tools > Trowels Hawk and Float',
  'Tools and Machinery > Hand Tools > Wire Brushes and Sanding Blocks',
  'Tools and Machinery > Hand Tools > Wrenches',
  'Tools and Machinery > Machine Accessories > Compressor Accessories',
  'Tools and Machinery > Machine Accessories > Generator Accessories',
  'Tools and Machinery > Machine Accessories > Welding Accessories',
  'Tools and Machinery > Machine Accessories > Woodwork Accessories',
  'Tools and Machinery > Machinery > Compressors',
  'Tools and Machinery > Machinery > Generators',
  'Tools and Machinery > Machinery > Pressure Washer',
  'Tools and Machinery > Machinery > Water Pumps',
  'Tools and Machinery > Machinery > Welding Machines',
  'Tools and Machinery > Measuring And Marking Tools > Electronic Measuring Tools',
  'Tools and Machinery > Measuring And Marking Tools > Markers and Chalk Tools',
  'Tools and Machinery > Measuring And Marking Tools > Measuring Tools',
  'Tools and Machinery > Power Tools > Blowers',
  'Tools and Machinery > Power Tools > Cordless Tools Batt and Acc',
  'Tools and Machinery > Power Tools > Drills',
  'Tools and Machinery > Power Tools > Engravers',
  'Tools and Machinery > Power Tools > Grinders',
  'Tools and Machinery > Power Tools > Heat Guns',
  'Tools and Machinery > Power Tools > Hobby Tools',
  'Tools and Machinery > Power Tools > Lathes',
  'Tools and Machinery > Power Tools > Planers',
  'Tools and Machinery > Power Tools > Power Tool Kits',
  'Tools and Machinery > Power Tools > Routers',
  'Tools and Machinery > Power Tools > Sander',
  'Tools and Machinery > Power Tools > Saws',
  'Tools and Machinery > Power Tools > Soldering',
  'Tools and Machinery > Power Tools > Soldering and Accessories',
  'Tools and Machinery > Saws Accessories > Circular Saw Blades',
  'Tools and Machinery > Saws Accessories > Cut off Discs',
  'Tools and Machinery > Saws Accessories > Hole Saw Accessories',
  'Tools and Machinery > Saws Accessories > Jigsaw and Bandsaw Blades',
  'Tools and Machinery > Shop By Tool Application > Building Tools',
  'Tools and Machinery > Shop By Tool Application > Electrical Tools',
  'Tools and Machinery > Shop By Tool Application > Mechanic Tools',
  'Tools and Machinery > Shop By Tool Application > Plumbing Tools',
  'Tools and Machinery > Shop By Tool Application > Tile Tools',
  'Tools and Machinery > Shop By Tool Application > Woodwork Tools',
  'Tools and Machinery > Tool Sets > Hand Tool Sets',
  'Tools and Machinery > Tool Sets > Rivetters and Rivets',
  'Tools and Machinery > Tool Sets > Screwdriver Sets',
  'Tools and Machinery > Tool Sets > Socket Sets',
  'Tools and Machinery > Tool Sets > Spanner Sets',
  'Tools and Machinery > Tool Sets > Tap and Die Sets',
  'Tools and Machinery > Tool Storage > Metal Tools Boxes',
  'Tools and Machinery > Tool Storage > Plastic Tool Boxes',
  'Tools and Machinery > Tool Storage > Tool Bags',
  'Water Tanks and Filtration > Water Storage > Water Tank Accessories',
  'Water Tanks and Filtration > Water Storage > Water Tank Pumps',
  'Water Tanks and Filtration > Water Storage > Watering Chemicals'
];

const slugify = (value: string) =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');

type NodeMap = Map<string, { id: string; label: string; children: NodeMap }>;

const buildCategoryTree = (paths: string[]): CategoryNode[] => {
  const root: NodeMap = new Map();

  for (const path of paths) {
    const segments = path.split('>').map(segment => segment.trim()).filter(Boolean);
    const slugParts: string[] = [];
    let level: NodeMap = root;

    for (const segment of segments) {
      slugParts.push(slugify(segment));
      if (!level.has(segment)) {
        level.set(segment, {
          id: slugParts.join('__'),
          label: segment,
          children: new Map(),
        });
      }
      level = level.get(segment)!.children;
    }
  }

  const toArray = (map: NodeMap): CategoryNode[] =>
    Array.from(map.values()).map(node => ({
      id: node.id,
      label: node.label,
      ...(node.children.size ? { children: toArray(node.children) } : {}),
    }));

  return toArray(root);
};

export const CATEGORY_TREE = buildCategoryTree(CATEGORY_PATHS);
