import { Product, Category, Store } from './types';

export { CATEGORY_TREE } from './categoryTree';

export const FREE_SHIPPING_THRESHOLD = 1000; // R1000 ZAR
export const CURRENCY_SYMBOL = 'R';

export const STORES: Store[] = [
  { id: '1', name: 'Belims Sandton', address: '12 Rivonia Rd, Sandton', distance: 2.5 },
  { id: '2', name: 'Belims Cape Town', address: '88 Strand St, Cape Town', distance: 1200 },
  { id: '3', name: 'Belims Durban', address: '45 West St, Durban', distance: 600 },
];

export const CATEGORIES: Category[] = [
  { id: 'power-tools', name: 'Power Tools', image: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=400&q=80', subcategories: ['Drills', 'Saws', 'Sanders', 'Grinders'] },
  { id: 'hand-tools', name: 'Hand Tools', image: 'https://images.unsplash.com/photo-1581235720704-06d3acfcb363?auto=format&fit=crop&w=400&q=80', subcategories: ['Hammers', 'Screwdrivers', 'Wrenches', 'Pliers'] },
  { id: 'building', name: 'Building Materials', image: 'https://images.unsplash.com/photo-aX-poWx3lRs?auto=format&fit=crop&w=400&q=80', subcategories: ['Cement', 'Bricks', 'Timber', 'Insulation'] },
  { id: 'paint', name: 'Paint & Supplies', image: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&w=400&q=80', subcategories: ['Interior', 'Exterior', 'Primers', 'Brushes'] },
  { id: 'safety', name: 'Safety Gear', image: 'https://images.unsplash.com/photo-1593307315564-c96172dc89dc?q=80&w=772&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', subcategories: ['Helmets', 'Gloves', 'Boots', 'Goggles'] },
];

// CORE HARDWARE PRODUCTS - Synced from WooCommerce 2025-11-26 (30 products captured, 23 with complete pricing)
export const SYNCED_PRODUCTS: Product[] = [
  {
    id: '20v-lithium-ion-battery-and-charger-kit',
    name: '20V Lithium-Ion Battery And Charger Kit',
    category: 'Cordless Tools Batt and Acc',
    price: 688.85,
    image: 'https://staging.belims.co.za/wp-content/uploads/2025/05/6070f46fde67bacca245b32d9981478b.png',
    rating: 4,
    reviews: 20,
    stock: 2,
    maxStock: 4,
    brand: 'Cordless Tools Batt and Acc',
    sku: 'FBCPK1222',
    description: '20V Lithium-Ion Battery And Charger Kit ships directly from Belims staging warehouse.',
    tags: ['cordless-tools-batt-and-acc', 'power-tools', 'tools-and-machinery'],
    features: ['Live SKU FBCPK1222', 'Includes 15% VAT for storefront parity', '2 in stock']
  },
  {
    id: 'staples-3',
    name: 'Staples',
    category: 'Fasteners and Adhesives',
    price: 92.01,
    image: 'https://staging.belims.co.za/wp-content/uploads/2025/05/cfd58a70e94ac20b56e163b137c8b0f7.png',
    rating: 4.2,
    reviews: 25,
    stock: 5,
    maxStock: 10,
    brand: 'Fasteners and Adhesives',
    sku: 'STS6110',
    description: 'Staples ships directly from Belims staging warehouse.',
    tags: ['fasteners-and-adhesives', 'nail-in-anchors', 'nails'],
    features: ['Live SKU STS6110', 'Includes 15% VAT for storefront parity', '5 in stock']
  },
  {
    id: 'tool-vest',
    name: 'Tool Vest',
    category: 'Uncategorized',
    price: 575,
    image: 'https://staging.belims.co.za/wp-content/uploads/2025/05/996dc2ab1b5c25ffb40d4b22fdffa9b8.png',
    rating: 4.4,
    reviews: 30,
    stock: 4,
    maxStock: 8,
    brand: 'Uncategorized',
    sku: 'HTVT09028',
    description: 'Tool Vest ships directly from Belims staging warehouse.',
    tags: [],
    features: ['Live SKU HTVT09028', 'Includes 15% VAT for storefront parity', '4 in stock']
  },
  {
    id: 'hex-chisel-2',
    name: 'Hex Chisel',
    category: 'Chisels and Crowbar',
    price: 143.76,
    image: 'https://staging.belims.co.za/wp-content/uploads/2025/05/26ee14c71e371ec2e2295d12a9dfaf08.png',
    rating: 4,
    reviews: 45,
    stock: 0,
    maxStock: 0,
    brand: 'Chisels and Crowbar',
    sku: 'DBC0522802',
    description: 'Hex Chisel ships directly from Belims staging warehouse.',
    tags: ['chisels-and-crowbar', 'hand-tools', 'tools-and-machinery'],
    features: ['Live SKU DBC0522802', 'Includes 15% VAT for storefront parity', 'Out of stock']
  },
  {
    id: 't-handle-torx-wrench-set',
    name: 'T-Handle Torx Wrench Set',
    category: 'Hand Tools',
    price: 436.99,
    image: 'https://staging.belims.co.za/wp-content/uploads/2025/05/e6e92c7c1968d0adc9eeb6aa9a057a36.png',
    rating: 4.4,
    reviews: 55,
    stock: 3,
    maxStock: 6,
    brand: 'Hand Tools',
    sku: 'HHKT80838',
    description: 'T-Handle Torx Wrench Set ships directly from Belims staging warehouse.',
    tags: ['hand-tools', 'screwdrivers-and-allen-keys', 'tools-and-machinery'],
    features: ['Live SKU HHKT80838', 'Includes 15% VAT for storefront parity', '3 in stock']
  },
  {
    id: 'screwdriver-set-3',
    name: 'Screwdriver Set',
    category: 'Hand Tools',
    price: 98.9,
    image: 'https://staging.belims.co.za/wp-content/uploads/2025/05/51a134ec518b8a4988d5784bf032dc6e.png',
    rating: 4.6,
    reviews: 60,
    stock: 0,
    maxStock: 0,
    brand: 'Hand Tools',
    sku: 'HKSD0428',
    description: 'Screwdriver Set ships directly from Belims staging warehouse.',
    tags: ['hand-tools', 'screwdrivers-and-allen-keys', 'tools-and-machinery'],
    features: ['Live SKU HKSD0428', 'Includes 15% VAT for storefront parity', 'Out of stock']
  },
  {
    id: 'high-pressure-washer-2',
    name: 'High Pressure Washer',
    category: 'Uncategorized',
    price: 8567.5,
    image: 'https://staging.belims.co.za/wp-content/uploads/2025/05/6de07d56a0b81afc657ca0334b4106e4.png',
    rating: 4,
    reviews: 70,
    stock: 0,
    maxStock: 0,
    brand: 'Uncategorized',
    sku: 'HPWR25008',
    description: 'High Pressure Washer ships directly from Belims staging warehouse.',
    tags: [],
    features: ['Live SKU HPWR25008', 'Includes 15% VAT for storefront parity', 'Out of stock']
  },
  {
    id: 'compound-combination-plier',
    name: 'Compound Combination Plier',
    category: 'Hand Tools',
    price: 278.29,
    image: 'https://staging.belims.co.za/wp-content/uploads/2025/05/09912837cec64f65144d3a9e4dae045e.png',
    rating: 4.8,
    reviews: 90,
    stock: 5,
    maxStock: 10,
    brand: 'Hand Tools',
    sku: 'HCCP58200',
    description: 'Compound Combination Plier ships directly from Belims staging warehouse.',
    tags: ['hand-tools', 'pliers', 'tools-and-machinery'],
    features: ['Live SKU HCCP58200', 'Includes 15% VAT for storefront parity', '5 in stock']
  },
  {
    id: 'circular-saw',
    name: 'Circular Saw',
    category: 'Power Tools',
    price: 1610,
    image: 'https://staging.belims.co.za/wp-content/uploads/2025/05/a464db7f1878636d67dc8eb2f885fa4a.png',
    rating: 4,
    reviews: 95,
    stock: 10,
    maxStock: 20,
    brand: 'Power Tools',
    sku: 'CS18538',
    description: 'Circular Saw ships directly from Belims staging warehouse.',
    tags: ['power-tools', 'saws', 'tools-and-machinery'],
    features: ['Live SKU CS18538', 'Includes 15% VAT for storefront parity', '10 in stock']
  },
  {
    id: 'rotary-hammer',
    name: 'Rotary Hammer',
    category: 'Drills',
    price: 3795.01,
    image: 'https://staging.belims.co.za/wp-content/uploads/2025/05/d878cac030ef0b45cc4c698c995cc382.png',
    rating: 4.2,
    reviews: 100,
    stock: 2,
    maxStock: 4,
    brand: 'Drills',
    sku: 'RH1600388',
    description: 'Rotary Hammer ships directly from Belims staging warehouse.',
    tags: ['drills', 'power-tools', 'tools-and-machinery'],
    features: ['Live SKU RH1600388', 'Includes 15% VAT for storefront parity', '2 in stock']
  },
  {
    id: '20v-lithium-ion-drive-ratchet',
    name: '20V Lithium-Ion Drive Ratchet',
    category: 'Uncategorized',
    price: 2875,
    image: 'https://staging.belims.co.za/wp-content/uploads/2025/05/03806ac4b9ca5c36cfc804fce1400909.png',
    rating: 4.4,
    reviews: 105,
    stock: 62,
    maxStock: 124,
    brand: 'Uncategorized',
    sku: 'CDRLI206015',
    description: '20V Lithium-Ion Drive Ratchet ships directly from Belims staging warehouse.',
    tags: [],
    features: ['Live SKU CDRLI206015', 'Includes 15% VAT for storefront parity', '62 in stock']
  },
  {
    id: '20v-lithium-ion-sheet-sander',
    name: '20V Lithium-Ion sheet sander',
    category: 'Power Tools',
    price: 920,
    image: 'https://staging.belims.co.za/wp-content/uploads/2025/05/d2338287a98cddbf2c4578327e49e183.png',
    rating: 4.6,
    reviews: 110,
    stock: 1,
    maxStock: 3,
    brand: 'Power Tools',
    sku: 'CSHSLI2014',
    description: '20V Lithium-Ion sheet sander ships directly from Belims staging warehouse.',
    tags: ['power-tools', 'sander', 'tools-and-machinery'],
    features: ['Live SKU CSHSLI2014', 'Includes 15% VAT for storefront parity', '1 in stock']
  },
  {
    id: 'lithium-ion-cordless-2-piece-combo-kit',
    name: 'Lithium-ion Cordless 2 Piece combo kit',
    category: 'Hand Tools',
    price: 3910,
    image: 'https://staging.belims.co.za/wp-content/uploads/2025/05/88a5cd1bbf3f426920ca5fc07eceb3a2.png',
    rating: 4.8,
    reviews: 115,
    stock: 10,
    maxStock: 20,
    brand: 'Hand Tools',
    sku: 'COSLI23011',
    description: 'Lithium-ion Cordless 2 Piece combo kit ships directly from Belims staging warehouse.',
    tags: ['hand-tools', 'tools-and-machinery', 'wrenches'],
    features: ['Live SKU COSLI23011', 'Includes 15% VAT for storefront parity', '10 in stock']
  },
  {
    id: '20v-lithium-ion-circular-saw',
    name: '20V Lithium-Ion Circular Saw',
    category: 'Power Tools',
    price: 1896.35,
    image: 'https://staging.belims.co.za/wp-content/uploads/2025/05/383e87c47e50b4f6be114b8ce7be8080.png',
    rating: 4,
    reviews: 120,
    stock: 0,
    maxStock: 0,
    brand: 'Power Tools',
    sku: 'CSLI18511',
    description: '20V Lithium-Ion Circular Saw ships directly from Belims staging warehouse.',
    tags: ['power-tools', 'saws', 'tools-and-machinery'],
    features: ['Live SKU CSLI18511', 'Includes 15% VAT for storefront parity', 'Out of stock']
  },
  {
    id: '40v-lithium-ion-chain-saw',
    name: '40V Lithium-Ion Chain Saw',
    category: 'Uncategorized',
    price: 4025,
    image: 'https://staging.belims.co.za/wp-content/uploads/2025/05/bb7988d64a589c350f3eae9b3e5139a7.png',
    rating: 4.2,
    reviews: 125,
    stock: 2,
    maxStock: 4,
    brand: 'Uncategorized',
    sku: 'CGSLI401682',
    description: '40V Lithium-Ion Chain Saw ships directly from Belims staging warehouse.',
    tags: [],
    features: ['Live SKU CGSLI401682', 'Includes 15% VAT for storefront parity', '2 in stock']
  },
  {
    id: '20v-lithium-ion-angle-grinder',
    name: '20V Lithium-Ion angle grinder',
    category: 'Grinders',
    price: 1092.5,
    image: 'https://staging.belims.co.za/wp-content/uploads/2025/05/9dfcb67a29288078c0f65d6156f39ef7.png',
    rating: 4.4,
    reviews: 130,
    stock: 21,
    maxStock: 42,
    brand: 'Grinders',
    sku: 'CAGLI21154',
    description: '20V Lithium-Ion angle grinder ships directly from Belims staging warehouse.',
    tags: ['grinders', 'power-tools', 'tools-and-machinery'],
    features: ['Live SKU CAGLI21154', 'Includes 15% VAT for storefront parity', '21 in stock']
  },
  {
    id: 'lithium-ion-compact-brushless-impact-drill',
    name: 'Lithium-Ion compact brushless impact drill',
    category: 'Drills',
    price: 977.5,
    image: 'https://staging.belims.co.za/wp-content/uploads/2025/05/60550b6742c225df53293d3377c78694.png',
    rating: 4.6,
    reviews: 135,
    stock: 2,
    maxStock: 4,
    brand: 'Drills',
    sku: 'CIDLI206021',
    description: 'Lithium-Ion compact brushless impact drill ships directly from Belims staging warehouse.',
    tags: ['drills', 'power-tools', 'tools-and-machinery'],
    features: ['Live SKU CIDLI206021', 'Includes 15% VAT for storefront parity', '2 in stock']
  },
  {
    id: 'fencing-pliers',
    name: 'Fencing Pliers',
    category: 'Hand Tools',
    price: 287.5,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/11/41de02a721e817136bd7c3d8916882ee.png',
    rating: 4.8,
    reviews: 140,
    stock: 2,
    maxStock: 4,
    brand: 'Hand Tools',
    sku: 'HFP2508',
    description: 'Fencing Pliers ships directly from Belims staging warehouse.',
    tags: ['hand-tools', 'pliers', 'tools-and-machinery'],
    features: ['Live SKU HFP2508', 'Includes 15% VAT for storefront parity', '2 in stock']
  },
  {
    id: 'self-leveling-line-laser-green-laser-beams-2',
    name: 'Self-Leveling Line Laser (Green Laser Beams)',
    category: 'Hand Tools',
    price: 5748.85,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/7a1668c2b782c3be43fb4c809ddad810.png',
    rating: 4,
    reviews: 145,
    stock: 0,
    maxStock: 0,
    brand: 'Hand Tools',
    sku: 'HLL305205',
    description: 'Self-Leveling Line Laser (Green Laser Beams) ships directly from Belims staging warehouse.',
    tags: ['hand-tools', 'levels-and-accessories', 'tools-and-machinery'],
    features: ['Live SKU HLL305205', 'Includes 15% VAT for storefront parity', 'Out of stock']
  },
  {
    id: 'self-leveling-line-laser-green-laser-beams',
    name: 'Self-Leveling Line Laser (Green Laser Beams)',
    category: 'Hand Tools',
    price: 1897.5,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/e260150345f6194bda9ac2639039238d.png',
    rating: 4.2,
    reviews: 150,
    stock: 0,
    maxStock: 0,
    brand: 'Hand Tools',
    sku: 'HLL156508',
    description: 'Self-Leveling Line Laser (Green Laser Beams) ships directly from Belims staging warehouse.',
    tags: ['hand-tools', 'levels-and-accessories', 'tools-and-machinery'],
    features: ['Live SKU HLL156508', 'Includes 15% VAT for storefront parity', 'Out of stock']
  },
  {
    id: 'flexible-ratchet-spanner-set',
    name: 'Flexible Ratchet Spanner Set',
    category: 'Hand Tools',
    price: 1259.25,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/9f70fad70bdd92982d2dcb3fbaf50e9e.png',
    rating: 4.4,
    reviews: 155,
    stock: 0,
    maxStock: 0,
    brand: 'Hand Tools',
    sku: 'HKSPAR1083',
    description: 'Flexible Ratchet Spanner Set ships directly from Belims staging warehouse.',
    tags: ['hand-tools', 'spanners-and-sockets', 'tools-and-machinery'],
    features: ['Live SKU HKSPAR1083', 'Includes 15% VAT for storefront parity', 'Out of stock']
  },
  {
    id: 'retractable-utility-knife',
    name: 'Retractable Utility Knife',
    category: 'Uncategorized',
    price: 36.8,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/e5ca481406a869c0dcba87d3c1b008bf.png',
    rating: 4.6,
    reviews: 160,
    stock: 0,
    maxStock: 0,
    brand: 'Uncategorized',
    sku: 'HKNS11615',
    description: 'Retractable Utility Knife ships directly from Belims staging warehouse.',
    tags: [],
    features: ['Live SKU HKNS11615', 'Includes 15% VAT for storefront parity', 'Out of stock']
  },
  {
    id: 'knife',
    name: 'Knife',
    category: 'Uncategorized',
    price: 49.45,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/31753ee84e6ef665a5026e94ddd66257.png',
    rating: 4.8,
    reviews: 165,
    stock: 1,
    maxStock: 3,
    brand: 'Uncategorized',
    sku: 'HKNS28035',
    description: 'Knife ships directly from Belims staging warehouse.',
    tags: [],
    features: ['Live SKU HKNS28035', 'Includes 15% VAT for storefront parity', '1 in stock']
  },
  {
    id: 'staples-2',
    name: 'Staples',
    category: 'Electrical Hand Tools',
    price: 25.3,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/3cec18660871145fcbf71f0d85242e7e.png',
    rating: 4,
    reviews: 20,
    stock: 1,
    maxStock: 3,
    brand: 'Electrical Hand Tools',
    sku: 'STS0112',
    description: 'Staples ships directly from Belims staging warehouse.',
    tags: ['electrical-hand-tools', 'staple-guns-and-staples', 'tools-and-machinery'],
    features: ['Live SKU STS0112', 'Includes 15% VAT for storefront parity', '1 in stock']
  },
  {
    id: 'socket-set-5',
    name: 'Socket Set',
    category: 'Hand Tools',
    price: 0,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/7194f34b49a733508e0e3bc894d90c6d.png',
    rating: 4.2,
    reviews: 25,
    stock: 1,
    maxStock: 3,
    brand: 'Hand Tools',
    sku: 'HKTS12103',
    description: 'Socket Set ships directly from Belims staging warehouse.',
    tags: ['hand-tools', 'spanners-and-sockets', 'tools-and-machinery'],
    features: ['Live SKU HKTS12103', 'Includes 15% VAT for storefront parity', '1 in stock']
  },
  {
    id: '20v-lithium-ion-cordless-screwdriver',
    name: '20V Lithium-Ion Cordless Screwdriver',
    category: 'Uncategorized',
    price: 8280,
    image: 'https://staging.belims.co.za/wp-content/uploads/2025/05/6c1ec97902d64adca561dc326e051756.png',
    rating: 4.4,
    reviews: 30,
    stock: 0,
    maxStock: 0,
    brand: 'Uncategorized',
    sku: 'CSDLI0413',
    description: '20V Lithium-Ion Cordless Screwdriver ships directly from Belims staging warehouse.',
    tags: [],
    features: ['Live SKU CSDLI0413', 'Includes 15% VAT for storefront parity', 'Out of stock']
  },
  {
    id: 'cordless-screwdriver-4v-with-bits',
    name: 'Cordless Screwdriver 4V with Bits',
    category: 'None',
    price: 722.2,
    image: 'https://staging.belims.co.za/wp-content/uploads/2025/05/9371261f2c3823c616882839756a70a8.png',
    rating: 4.6,
    reviews: 35,
    stock: 66,
    maxStock: 132,
    brand: 'None',
    sku: 'CSDLI0403',
    description: 'Cordless Screwdriver 4V with Bits ships directly from Belims staging warehouse.',
    tags: ['none', 'tools-and-machinery'],
    features: ['Live SKU CSDLI0403', 'Includes 15% VAT for storefront parity', '66 in stock']
  },
  {
    id: '20v-ps-brad-nailer',
    name: '20V Ps+ Brad Nailer',
    category: 'None',
    price: 4025,
    image: 'https://staging.belims.co.za/wp-content/uploads/2025/05/027cc10df5a689138fa49cd4710189cf.png',
    rating: 4.8,
    reviews: 40,
    stock: 8,
    maxStock: 16,
    brand: 'None',
    sku: 'CBNLI2028',
    description: '20V Ps+ Brad Nailer ships directly from Belims staging warehouse.',
    tags: ['none', 'tools-and-machinery'],
    features: ['Live SKU CBNLI2028', 'Includes 15% VAT for storefront parity', '8 in stock']
  },
  {
    id: 'socket-set-4',
    name: 'Socket Set',
    category: 'Hand Tools',
    price: 0,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/a772f652f4c1f2da9a7c1bcb42245933.png',
    rating: 4,
    reviews: 45,
    stock: 0,
    maxStock: 0,
    brand: 'Hand Tools',
    sku: 'HKTS14103',
    description: 'Socket Set ships directly from Belims staging warehouse.',
    tags: ['hand-tools', 'spanners-and-sockets', 'tools-and-machinery'],
    features: ['Live SKU HKTS14103', 'Includes 15% VAT for storefront parity', 'Out of stock']
  },
  {
    id: 'plier-set-2',
    name: 'Plier Set',
    category: 'Hand Tools',
    price: 0,
    image: 'https://staging.belims.co.za/wp-content/uploads/2025/05/bc0fba4785e78a67f61deac0b3f6bd13.png',
    rating: 4.2,
    reviews: 50,
    stock: 3,
    maxStock: 6,
    brand: 'Hand Tools',
    sku: 'HKPS08212',
    description: 'Plier Set ships directly from Belims staging warehouse.',
    tags: ['hand-tools', 'pliers', 'tools-and-machinery'],
    features: ['Live SKU HKPS08212', 'Includes 15% VAT for storefront parity', '3 in stock']
  },
  {
    id: 'water-pump-plier-3',
    name: 'Water Pump Plier',
    category: 'Hand Tools',
    price: 0,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/784da671d5b298ab76572b11bce38f2a.png',
    rating: 4.4,
    reviews: 55,
    stock: 0,
    maxStock: 0,
    brand: 'Hand Tools',
    sku: 'HPP28251',
    description: 'Water Pump Plier ships directly from Belims staging warehouse.',
    tags: ['hand-tools', 'pliers', 'tools-and-machinery'],
    features: ['Live SKU HPP28251', 'Includes 15% VAT for storefront parity', 'Out of stock']
  },
  {
    id: 'plier-combination-160mm-anti-rust',
    name: 'PLIER COMBINATION 160MM ANTI RUST',
    category: 'Hand Tools',
    price: 0,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/50b6f555096347388640be98e228ed8d.png',
    rating: 4.6,
    reviews: 60,
    stock: 2,
    maxStock: 4,
    brand: 'Hand Tools',
    sku: 'HCP12160',
    description: 'PLIER COMBINATION 160MM ANTI RUST ships directly from Belims staging warehouse.',
    tags: ['hand-tools', 'pliers', 'tools-and-machinery'],
    features: ['Live SKU HCP12160', 'Includes 15% VAT for storefront parity', '2 in stock']
  },
  {
    id: 'brad-nail-3',
    name: 'Brad Nail',
    category: 'Fasteners and Adhesives',
    price: 0,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/646e7178e023173be1e8273ac5a72072.png',
    rating: 4.8,
    reviews: 65,
    stock: 1,
    maxStock: 3,
    brand: 'Fasteners and Adhesives',
    sku: 'ANA18301',
    description: 'Brad Nail ships directly from Belims staging warehouse.',
    tags: ['fasteners-and-adhesives', 'nails', 'nails-nails'],
    features: ['Live SKU ANA18301', 'Includes 15% VAT for storefront parity', '1 in stock']
  },
  {
    id: 'multi-functional-kitchen-scissors',
    name: 'Multi-Functional Kitchen Scissors',
    category: 'Bolt Cutters and Tin Snip',
    price: 103.5,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/edad465725fcfa38558bf79854c83d53.png',
    rating: 4,
    reviews: 20,
    stock: 6,
    maxStock: 12,
    brand: 'Bolt Cutters and Tin Snip',
    sku: 'HSCRS822251',
    description: 'Multi-Functional Kitchen Scissors ships directly from Belims staging warehouse.',
    tags: ['bolt-cutters-and-tin-snip', 'hand-tools', 'tools-and-machinery'],
    features: ['Live SKU HSCRS822251', 'Includes 15% VAT for storefront parity', '6 in stock']
  },
  {
    id: 'plier-l-nose-160mm-anti-rust',
    name: 'PLIER L/NOSE 160MM ANTI RUST',
    category: 'Hand Tools',
    price: 0,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/9cc2007315c47edf2dc656d94234b546.png',
    rating: 4.2,
    reviews: 25,
    stock: 0,
    maxStock: 0,
    brand: 'Hand Tools',
    sku: 'HLNP12160',
    description: 'PLIER L/NOSE 160MM ANTI RUST ships directly from Belims staging warehouse.',
    tags: ['hand-tools', 'pliers', 'tools-and-machinery'],
    features: ['Live SKU HLNP12160', 'Includes 15% VAT for storefront parity', 'Out of stock']
  },
  {
    id: 'bench-vice-4',
    name: 'Bench Vice',
    category: 'Uncategorized',
    price: 0,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/f6906c543fca5cc7a83adde6c65d76d3.png',
    rating: 4.4,
    reviews: 30,
    stock: 0,
    maxStock: 0,
    brand: 'Uncategorized',
    sku: 'HBV088',
    description: 'Bench Vice ships directly from Belims staging warehouse.',
    tags: [],
    features: ['Live SKU HBV088', 'Includes 15% VAT for storefront parity', 'Out of stock']
  },
  {
    id: 'bench-vice-3',
    name: 'Bench Vice',
    category: 'Uncategorized',
    price: 0,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/3c5d541e883e55f7db6ad134f8fae234.png',
    rating: 4.6,
    reviews: 35,
    stock: 1,
    maxStock: 3,
    brand: 'Uncategorized',
    sku: 'HBV086',
    description: 'Bench Vice ships directly from Belims staging warehouse.',
    tags: [],
    features: ['Live SKU HBV086', 'Includes 15% VAT for storefront parity', '1 in stock']
  },
  {
    id: 'bench-vice-2',
    name: 'Bench Vice',
    category: 'Uncategorized',
    price: 0,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/6174005d8e4af0d1508f4b64ddb105f9.png',
    rating: 4.8,
    reviews: 40,
    stock: 0,
    maxStock: 0,
    brand: 'Uncategorized',
    sku: 'HBV084',
    description: 'Bench Vice ships directly from Belims staging warehouse.',
    tags: [],
    features: ['Live SKU HBV084', 'Includes 15% VAT for storefront parity', 'Out of stock']
  },
  {
    id: 'bench-vice',
    name: 'Bench Vice',
    category: 'Uncategorized',
    price: 0,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/ef22967bf8e3286c8143149e107d47de.png',
    rating: 4,
    reviews: 45,
    stock: 0,
    maxStock: 0,
    brand: 'Uncategorized',
    sku: 'HBV082',
    description: 'Bench Vice ships directly from Belims staging warehouse.',
    tags: [],
    features: ['Live SKU HBV082', 'Includes 15% VAT for storefront parity', 'Out of stock']
  },
  {
    id: 'heavy-duty-greace-gun',
    name: 'Heavy Duty Greace Gun',
    category: 'Uncategorized',
    price: 0,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/0549aa814519cae09771305e660e86d9.png',
    rating: 4.2,
    reviews: 50,
    stock: 0,
    maxStock: 0,
    brand: 'Uncategorized',
    sku: 'GRG015001',
    description: 'Heavy Duty Greace Gun ships directly from Belims staging warehouse.',
    tags: [],
    features: ['Live SKU GRG015001', 'Includes 15% VAT for storefront parity', 'Out of stock']
  },
  {
    id: 'glue-gun',
    name: 'Glue Gun',
    category: 'Uncategorized',
    price: 458.85,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/51120af36d3911f7c203e5917859737c.png',
    rating: 4.4,
    reviews: 55,
    stock: 0,
    maxStock: 0,
    brand: 'Uncategorized',
    sku: 'GG308',
    description: 'Glue Gun ships directly from Belims staging warehouse.',
    tags: [],
    features: ['Live SKU GG308', 'Includes 15% VAT for storefront parity', 'Out of stock']
  },
  {
    id: 'longnose-plier',
    name: 'Longnose Plier',
    category: 'Hand Tools',
    price: 103.5,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/0c6902ceff383b601665a603ac4f1ab9.png',
    rating: 4.6,
    reviews: 60,
    stock: 0,
    maxStock: 0,
    brand: 'Hand Tools',
    sku: 'HILNP28168',
    description: 'Longnose Plier ships directly from Belims staging warehouse.',
    tags: ['hand-tools', 'pliers', 'tools-and-machinery'],
    features: ['Live SKU HILNP28168', 'Includes 15% VAT for storefront parity', 'Out of stock']
  },
  {
    id: 'diagonal-plier-4',
    name: 'Diagonal Plier',
    category: 'Hand Tools',
    price: 0,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/82ff8b45fae0b8344149f987d0f41f48.png',
    rating: 4.8,
    reviews: 65,
    stock: 0,
    maxStock: 0,
    brand: 'Hand Tools',
    sku: 'HIHLDCP28160',
    description: 'Diagonal Plier ships directly from Belims staging warehouse.',
    tags: ['hand-tools', 'pliers', 'tools-and-machinery'],
    features: ['Live SKU HIHLDCP28160', 'Includes 15% VAT for storefront parity', 'Out of stock']
  },
  {
    id: 'aluminum-caulking-gun',
    name: 'Aluminum Caulking Gun',
    category: 'Uncategorized',
    price: 253,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/db116783674bea6dc45f01f6aab0ff4b.png',
    rating: 4,
    reviews: 70,
    stock: 0,
    maxStock: 0,
    brand: 'Uncategorized',
    sku: 'HCG0112',
    description: 'Aluminum Caulking Gun ships directly from Belims staging warehouse.',
    tags: [],
    features: ['Live SKU HCG0112', 'Includes 15% VAT for storefront parity', 'Out of stock']
  },
  {
    id: 'air-tools-set',
    name: 'Air Tools Set',
    category: 'Uncategorized',
    price: 0,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/2efcc298bfcf01637ba07b27f3ecba29.png',
    rating: 4.2,
    reviews: 75,
    stock: 4,
    maxStock: 8,
    brand: 'Uncategorized',
    sku: 'AKT0051',
    description: 'Air Tools Set ships directly from Belims staging warehouse.',
    tags: [],
    features: ['Live SKU AKT0051', 'Includes 15% VAT for storefront parity', '4 in stock']
  },
  {
    id: 'ratchet-screwdriver-set',
    name: 'Ratchet Screwdriver Set',
    category: 'Uncategorized',
    price: 0,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/fb6329652868cfa08c03392da9daf989.png',
    rating: 4.4,
    reviews: 80,
    stock: 6,
    maxStock: 12,
    brand: 'Uncategorized',
    sku: 'AKISD1208',
    description: 'Ratchet Screwdriver Set ships directly from Belims staging warehouse.',
    tags: [],
    features: ['Live SKU AKISD1208', 'Includes 15% VAT for storefront parity', '6 in stock']
  },
  {
    id: 'ratchet-screwdriver',
    name: 'Ratchet Screwdriver',
    category: 'Hand Tools',
    price: 0,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/2259c8fdf4e10c9a487de5162a552ff4.png',
    rating: 4.6,
    reviews: 85,
    stock: 0,
    maxStock: 0,
    brand: 'Hand Tools',
    sku: 'AKISD0808',
    description: 'Ratchet Screwdriver ships directly from Belims staging warehouse.',
    tags: ['hand-tools', 'screwdrivers-and-allen-keys', 'tools-and-machinery'],
    features: ['Live SKU AKISD0808', 'Includes 15% VAT for storefront parity', 'Out of stock']
  },
  {
    id: 'screwdriver-set-2',
    name: 'Screwdriver Set',
    category: 'Hand Tools',
    price: 0,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/be1e4f759efb414f48968940df5afe3d.png',
    rating: 4.8,
    reviews: 90,
    stock: 11,
    maxStock: 22,
    brand: 'Hand Tools',
    sku: 'AKISD0608',
    description: 'Screwdriver Set ships directly from Belims staging warehouse.',
    tags: ['hand-tools', 'screwdrivers-and-allen-keys', 'tools-and-machinery'],
    features: ['Live SKU AKISD0608', 'Includes 15% VAT for storefront parity', '11 in stock']
  },
  {
    id: 'air-hose-3',
    name: 'Air Hose',
    category: 'Uncategorized',
    price: 0,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/97907adab0f6506ece0982dba6dc8b58.png',
    rating: 4,
    reviews: 95,
    stock: 3,
    maxStock: 6,
    brand: 'Uncategorized',
    sku: 'AH1151',
    description: 'Air Hose ships directly from Belims staging warehouse.',
    tags: [],
    features: ['Live SKU AH1151', 'Includes 15% VAT for storefront parity', '3 in stock']
  },
  {
    id: 'air-hose-2',
    name: 'Air Hose',
    category: 'Uncategorized',
    price: 0,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/bd17f2137b8c388dcf8c2c2a1fc68a92.png',
    rating: 4.2,
    reviews: 100,
    stock: 0,
    maxStock: 0,
    brand: 'Uncategorized',
    sku: 'AH1101',
    description: 'Air Hose ships directly from Belims staging warehouse.',
    tags: [],
    features: ['Live SKU AH1101', 'Includes 15% VAT for storefront parity', 'Out of stock']
  },
  {
    id: 'air-hose',
    name: 'Air Hose',
    category: 'Uncategorized',
    price: 0,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/faf03f27799ae93d563c55ad75f67cb9.png',
    rating: 4.4,
    reviews: 105,
    stock: 1,
    maxStock: 3,
    brand: 'Uncategorized',
    sku: 'AH1051',
    description: 'Air Hose ships directly from Belims staging warehouse.',
    tags: [],
    features: ['Live SKU AH1051', 'Includes 15% VAT for storefront parity', '1 in stock']
  },
  {
    id: '20v-ps-cordless-charger-2-0ah',
    name: '20V PS+ Cordless Charger 2.0Ah',
    category: 'Cordless Tools Batt and Acc',
    price: 343.85,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/5342338c33c73f6157cd15c3dd859f4c.png',
    rating: 4.6,
    reviews: 110,
    stock: 26,
    maxStock: 52,
    brand: 'Cordless Tools Batt and Acc',
    sku: 'FCLI2001',
    description: '20V PS+ Cordless Charger 2.0Ah ships directly from Belims staging warehouse.',
    tags: ['cordless-tools-batt-and-acc', 'power-tools', 'tools-and-machinery'],
    features: ['Live SKU FCLI2001', 'Includes 15% VAT for storefront parity', '26 in stock']
  },
  {
    id: '20v-ps-cordless-battery-4-0ah',
    name: '20V PS+ Cordless Battery 4.0Ah',
    category: 'Cordless Tools Batt and Acc',
    price: 688.85,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/c56ec7e348179cfb4f43f629c0366a1a.png',
    rating: 4.8,
    reviews: 115,
    stock: 13,
    maxStock: 26,
    brand: 'Cordless Tools Batt and Acc',
    sku: 'FBLI2002',
    description: '20V PS+ Cordless Battery 4.0Ah ships directly from Belims staging warehouse.',
    tags: ['cordless-tools-batt-and-acc', 'power-tools', 'tools-and-machinery'],
    features: ['Live SKU FBLI2002', 'Includes 15% VAT for storefront parity', '13 in stock']
  },
  {
    id: 'glue-stick-11-2mm-x-300mm-1kg',
    name: 'Glue Stick 11.2mm x 300mm 1kg',
    category: 'Adhesives',
    price: 11.51,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/6301e76c8ccec6cf19df074339ff03b4.png',
    rating: 4,
    reviews: 120,
    stock: 412,
    maxStock: 824,
    brand: 'Adhesives',
    sku: 'AKTGS3011',
    description: 'Glue Stick 11.2mm x 300mm 1kg ships directly from Belims staging warehouse.',
    tags: ['adhesives', 'fasteners-and-adhesives', 'general-purpose-adhesive'],
    features: ['Live SKU AKTGS3011', 'Includes 15% VAT for storefront parity', '412 in stock']
  },
  {
    id: 'interchanging-screwdriver-set-9-piece',
    name: 'Interchanging Screwdriver Set - 9 Piece',
    category: 'Hand Tools',
    price: 228.85,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/3d933d419723ec613f0673aeeb74c381.png',
    rating: 4.2,
    reviews: 125,
    stock: 0,
    maxStock: 0,
    brand: 'Hand Tools',
    sku: 'AKISD0901',
    description: 'Interchanging Screwdriver Set - 9 Piece ships directly from Belims staging warehouse.',
    tags: ['hand-tools', 'screwdrivers-and-allen-keys', 'tools-and-machinery'],
    features: ['Live SKU AKISD0901', 'Includes 15% VAT for storefront parity', 'Out of stock']
  },
  {
    id: 'tct-saw-blade-115mm-x-40-teeth',
    name: 'TCT Saw Blade 115mm x 40 Teeth',
    category: 'Uncategorized',
    price: 109.25,
    image: 'https://staging.belims.co.za/wp-content/uploads/2025/05/c1af6909c8a28a94a818bbbba26e50b1.png',
    rating: 4.4,
    reviews: 130,
    stock: 0,
    maxStock: 0,
    brand: 'Uncategorized',
    sku: 'TSB111555',
    description: 'TCT Saw Blade 115mm x 40 Teeth ships directly from Belims staging warehouse.',
    tags: [],
    features: ['Live SKU TSB111555', 'Includes 15% VAT for storefront parity', 'Out of stock']
  },
  {
    id: 'disc-grind-steel-115mm-x-6-0mm-x-22-2mm',
    name: 'Disc Grind Steel 115mm x 6.0mm x 22.2mm',
    category: 'Abrasive Grinding Disc',
    price: 18.97,
    image: 'https://staging.belims.co.za/wp-content/uploads/2025/05/46db90b806c7481d2978d5d9527d645f.png',
    rating: 4.6,
    reviews: 135,
    stock: 0,
    maxStock: 0,
    brand: 'Abrasive Grinding Disc',
    sku: 'MGD601151',
    description: 'Disc Grind Steel 115mm x 6.0mm x 22.2mm ships directly from Belims staging warehouse.',
    tags: ['abrasive-grinding-disc', 'grinding-accessories', 'tools-and-machinery'],
    features: ['Live SKU MGD601151', 'Includes 15% VAT for storefront parity', 'Out of stock']
  },
  {
    id: 'disc-cut-steel-115-10-piece',
    name: 'Disc Cut Steel 115 - 10 Piece',
    category: 'Cut off Discs',
    price: 126.5,
    image: 'https://staging.belims.co.za/wp-content/uploads/2025/05/7178c1df36e92784308247099ef97567.png',
    rating: 4.8,
    reviews: 140,
    stock: 0,
    maxStock: 0,
    brand: 'Cut off Discs',
    sku: 'MCD121155',
    description: 'Disc Cut Steel 115 - 10 Piece ships directly from Belims staging warehouse.',
    tags: ['cut-off-discs', 'saws-accessories', 'tools-and-machinery'],
    features: ['Live SKU MCD121155', 'Includes 15% VAT for storefront parity', 'Out of stock']
  },
  {
    id: 'saw-chain',
    name: 'Saw Chain',
    category: 'Uncategorized',
    price: 0,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/622c60e0a4e904f40eb0d04cf8d40cf9.png',
    rating: 4,
    reviews: 145,
    stock: 0,
    maxStock: 0,
    brand: 'Uncategorized',
    sku: 'AGSC51801',
    description: 'Saw Chain ships directly from Belims staging warehouse.',
    tags: [],
    features: ['Live SKU AGSC51801', 'Includes 15% VAT for storefront parity', 'Out of stock']
  },
  {
    id: 'air-compressor',
    name: 'Air Compressor',
    category: 'Uncategorized',
    price: 0,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/ff337adf63531a40290109caf038191b.png',
    rating: 4.2,
    reviews: 150,
    stock: 1,
    maxStock: 3,
    brand: 'Uncategorized',
    sku: 'ACS112501',
    description: 'Air Compressor ships directly from Belims staging warehouse.',
    tags: [],
    features: ['Live SKU ACS112501', 'Includes 15% VAT for storefront parity', '1 in stock']
  },
  {
    id: 'air-brad-nailer',
    name: 'Air Brad Nailer',
    category: 'Uncategorized',
    price: 0,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/c4274e30fd3fab1d4f1359753e3cf69a.png',
    rating: 4.4,
    reviews: 155,
    stock: 1,
    maxStock: 3,
    brand: 'Uncategorized',
    sku: 'ABN15501',
    description: 'Air Brad Nailer ships directly from Belims staging warehouse.',
    tags: [],
    features: ['Live SKU ABN15501', 'Includes 15% VAT for storefront parity', '1 in stock']
  },
  {
    id: 'air-blow-gun',
    name: 'Air Blow Gun',
    category: 'Uncategorized',
    price: 0,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/c9c51c2b1171c8af6b95a2b1dd3d7821.png',
    rating: 4.6,
    reviews: 160,
    stock: 1,
    maxStock: 3,
    brand: 'Uncategorized',
    sku: 'ABG031',
    description: 'Air Blow Gun ships directly from Belims staging warehouse.',
    tags: [],
    features: ['Live SKU ABG031', 'Includes 15% VAT for storefront parity', '1 in stock']
  },
  {
    id: 'tct-blade-3',
    name: 'TCT Blade',
    category: 'Jigsaw and Bandsaw Blades',
    price: 0,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/78967b681a4dc4c8606d577077de7f9d.png',
    rating: 4.8,
    reviews: 165,
    stock: 0,
    maxStock: 0,
    brand: 'Jigsaw and Bandsaw Blades',
    sku: 'TSB118515',
    description: 'TCT Blade ships directly from Belims staging warehouse.',
    tags: ['jigsaw-and-bandsaw-blades', 'saws-accessories', 'tools-and-machinery'],
    features: ['Live SKU TSB118515', 'Includes 15% VAT for storefront parity', 'Out of stock']
  },
  {
    id: 'tct-blade-4',
    name: 'TCT Blade',
    category: 'Jigsaw and Bandsaw Blades',
    price: 0,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/78967b681a4dc4c8606d577077de7f9d.png',
    rating: 4.8,
    reviews: 165,
    stock: 0,
    maxStock: 0,
    brand: 'Jigsaw and Bandsaw Blades',
    sku: 'TSB118515',
    description: 'TCT Blade ships directly from Belims staging warehouse.',
    tags: ['jigsaw-and-bandsaw-blades', 'saws-accessories', 'tools-and-machinery'],
    features: ['Live SKU TSB118515', 'Includes 15% VAT for storefront parity', 'Out of stock']
  },
  {
    id: 'tct-blade-2',
    name: 'TCT Blade',
    category: 'Jigsaw and Bandsaw Blades',
    price: 0,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/796bcddbf9f058a83377fe187c16dc4b.png',
    rating: 4,
    reviews: 20,
    stock: 0,
    maxStock: 0,
    brand: 'Jigsaw and Bandsaw Blades',
    sku: 'TSB118513',
    description: 'TCT Blade ships directly from Belims staging warehouse.',
    tags: ['jigsaw-and-bandsaw-blades', 'saws-accessories', 'tools-and-machinery'],
    features: ['Live SKU TSB118513', 'Includes 15% VAT for storefront parity', 'Out of stock']
  },
  {
    id: 'tct-blade',
    name: 'TCT Blade',
    category: 'Jigsaw and Bandsaw Blades',
    price: 0,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/5d7543cd93370c69293a3fd181ff6b7d.png',
    rating: 4.2,
    reviews: 25,
    stock: 1,
    maxStock: 3,
    brand: 'Jigsaw and Bandsaw Blades',
    sku: 'TSB116511',
    description: 'TCT Blade ships directly from Belims staging warehouse.',
    tags: ['jigsaw-and-bandsaw-blades', 'saws-accessories', 'tools-and-machinery'],
    features: ['Live SKU TSB116511', 'Includes 15% VAT for storefront parity', '1 in stock']
  },
  {
    id: 'brad-naill-1x2x1-2mm-1000pc',
    name: 'BRAD NAILL 1X2X1.2MM 1000PC',
    category: 'Fasteners and Adhesives',
    price: 23,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/e349e297b92378056be94f953763d78d.png',
    rating: 4.4,
    reviews: 30,
    stock: 5,
    maxStock: 10,
    brand: 'Fasteners and Adhesives',
    sku: 'STS0310',
    description: 'BRAD NAILL 1X2X1.2MM 1000PC ships directly from Belims staging warehouse.',
    tags: ['fasteners-and-adhesives', 'nail-in-anchors', 'nails'],
    features: ['Live SKU STS0310', 'Includes 15% VAT for storefront parity', '5 in stock']
  },
  {
    id: 'staples',
    name: 'Staples',
    category: 'Electrical Hand Tools',
    price: 20.7,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/cbe7d6df4a1aeb360fa9d973db742978.png',
    rating: 4.6,
    reviews: 35,
    stock: 0,
    maxStock: 0,
    brand: 'Electrical Hand Tools',
    sku: 'STS0108',
    description: 'Staples ships directly from Belims staging warehouse.',
    tags: ['electrical-hand-tools', 'staple-guns-and-staples', 'tools-and-machinery'],
    features: ['Live SKU STS0108', 'Includes 15% VAT for storefront parity', 'Out of stock']
  },
  {
    id: 'blade-recip-2',
    name: 'Blade Recip',
    category: 'Jigsaw and Bandsaw Blades',
    price: 86.25,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/1cccb9cf5d4efa7f0065c14154c08b1d.png',
    rating: 4.8,
    reviews: 40,
    stock: 9,
    maxStock: 18,
    brand: 'Jigsaw and Bandsaw Blades',
    sku: 'SSB922EF',
    description: 'Blade Recip ships directly from Belims staging warehouse.',
    tags: ['jigsaw-and-bandsaw-blades', 'saws-accessories', 'tools-and-machinery'],
    features: ['Live SKU SSB922EF', 'Includes 15% VAT for storefront parity', '9 in stock']
  },
  {
    id: 'blade-recip',
    name: 'Blade Recip',
    category: 'Jigsaw and Bandsaw Blades',
    price: 40.24,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/01fbf3e99e988aaaa6be79b735cd8e86.png',
    rating: 4,
    reviews: 45,
    stock: 4,
    maxStock: 8,
    brand: 'Jigsaw and Bandsaw Blades',
    sku: 'SSB644D',
    description: 'Blade Recip ships directly from Belims staging warehouse.',
    tags: ['jigsaw-and-bandsaw-blades', 'saws-accessories', 'tools-and-machinery'],
    features: ['Live SKU SSB644D', 'Includes 15% VAT for storefront parity', '4 in stock']
  },
  {
    id: 'keyless-chuck',
    name: 'Keyless Chuck',
    category: 'Chucks and Keys',
    price: 155.25,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/b494f7378dd0c6d1d9680f9efa78c395.png',
    rating: 4.2,
    reviews: 50,
    stock: 0,
    maxStock: 0,
    brand: 'Chucks and Keys',
    sku: 'KCL1301',
    description: 'Keyless Chuck ships directly from Belims staging warehouse.',
    tags: ['chucks-and-keys', 'drill-accessories', 'tools-and-machinery'],
    features: ['Live SKU KCL1301', 'Includes 15% VAT for storefront parity', 'Out of stock']
  },
  {
    id: 'key-chuck-with-adaptor',
    name: 'Key Chuck With Adaptor',
    category: 'Chucks and Keys',
    price: 143.76,
    image: 'https://staging.belims.co.za/wp-content/uploads/2025/05/8c60e984e759329d9762508911101943.png',
    rating: 4.4,
    reviews: 55,
    stock: 2,
    maxStock: 4,
    brand: 'Chucks and Keys',
    sku: 'KC1301.1',
    description: 'Key Chuck With Adaptor ships directly from Belims staging warehouse.',
    tags: ['chucks-and-keys', 'drill-accessories', 'tools-and-machinery'],
    features: ['Live SKU KC1301.1', 'Includes 15% VAT for storefront parity', '2 in stock']
  },
  {
    id: 'jigsaw',
    name: 'Jigsaw',
    category: 'Power Tools',
    price: 917.7,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/000173ef681cc932a3a35f897e04ea57.png',
    rating: 4.6,
    reviews: 60,
    stock: 34,
    maxStock: 68,
    brand: 'Power Tools',
    sku: 'JS57028',
    description: 'Jigsaw ships directly from Belims staging warehouse.',
    tags: ['power-tools', 'saws', 'tools-and-machinery'],
    features: ['Live SKU JS57028', 'Includes 15% VAT for storefront parity', '34 in stock']
  },
  {
    id: 'wire-stripper-plier-2',
    name: 'Wire Stripper Plier',
    category: 'Hand Tools',
    price: 149.5,
    image: 'https://staging.belims.co.za/wp-content/uploads/2024/10/26ce3e3bc7b2c752d52f821ee5d74d01.png',
    rating: 4.8,
    reviews: 65,
    stock: 7,
    maxStock: 14,
    brand: 'Hand Tools',
    sku: 'HWSP851',
    description: 'Wire Stripper Plier ships directly from Belims staging warehouse.',
    tags: ['hand-tools', 'pliers', 'tools-and-machinery'],
    features: ['Live SKU HWSP851', 'Includes 15% VAT for storefront parity', '7 in stock']
  }
];

export const FEATURED_PRODUCTS: Product[] = SYNCED_PRODUCTS.slice(0, 4);
export const DEALS_PRODUCTS: Product[] = SYNCED_PRODUCTS.slice(4);

export const HERO_SLIDES = [
  {
    id: 1,
    title: "Build It Better",
    subtitle: "Up to 25% off DeWalt and Makita power tools this week.",
    image: "https://images.unsplash.com/photo-1581147036324-c17ac41dfa6c?auto=format&fit=crop&w=1600&q=80",
    cta: "Shop Power Tools"
  },
  {
    id: 2,
    title: "Contractors Warehouse",
    subtitle: "Bulk cement, bricks, and timber delivered to your site.",
    image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1600&q=80",
    cta: "Get A Quote"
  }
];

export const QUICK_LINKS = [];

export const PROJECT_IDEAS = [
  {
    id: 1,
    title: "Build a Floating Deck",
    description: "Everything you need from timber to screws to build the perfect outdoor deck.",
    image: "https://images.unsplash.com/photo-1591825729269-caeb344f6df2?auto=format&fit=crop&w=500&q=80",
    linkText: "Start Project"
  },
  {
    id: 2,
    title: "Bathroom Renovation",
    description: "Upgrade your fixtures, tiling, and plumbing for a modern look.",
    image: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?auto=format&fit=crop&w=500&q=80",
    linkText: "Shop Bathroom"
  },
  {
    id: 3,
    title: "Garage Workshop Setup",
    description: "Organize your tools with our range of storage and workbenches.",
    image: "https://images.unsplash.com/photo-1530124566582-a618bc2615dc?auto=format&fit=crop&w=500&q=80",
    linkText: "Get Organized"
  },
  {
    id: 4,
    title: "Interior Painting Guide",
    description: "Professional tips and the best primers for a flawless finish.",
    image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=500&q=80",
    linkText: "View Guide"
  }
];


export const CATEGORY_PILLS = [
  "Top Deals",
  "Power Tools",
  "Hand Tools",
  "Building Materials",
  "Paint & Decor",
  "Plumbing",
  "Electrical",
  "Safety Gear",
  "Garden"
];

const pickProducts = (predicate: (product: Product) => boolean, limit = 4): Product[] => {
  const matches = SYNCED_PRODUCTS.filter(predicate);
  if (matches.length >= limit) {
    return matches.slice(0, limit);
  }
  if (matches.length) {
    return [...matches, ...SYNCED_PRODUCTS].slice(0, limit);
  }
  return SYNCED_PRODUCTS.slice(0, limit);
};

const getProductsByTag = (tag: string, limit = 4) =>
  pickProducts(product => product.tags?.includes(tag) ?? false, limit);

const getProductsByCategory = (category: string, limit = 4) =>
  pickProducts(product => product.category === category, limit);

// Interactive Slider Data mapped to Hardware Categories
export const CATEGORY_SLIDER_DATA: Record<string, { title: string; image: string; products: Product[] }> = {
  "Top Deals": {
    title: "Pro-Grade Gear. Amateur Prices.",
    image: "https://images.unsplash.com/photo-1593307315564-c96172dc89dc?q=80&w=772&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    products: DEALS_PRODUCTS.slice(0, 4)
  },
  "Power Tools": {
    title: "Drill, Cut, Sand. Done.",
    image: "https://images.unsplash.com/photo-1593307315564-c96172dc89dc?q=80&w=772&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    products: getProductsByTag('power-tools')
  },
  "Hand Tools": {
    title: "Essential Tools for Every Toolbox.",
    image: "https://images.unsplash.com/photo-1593307315564-c96172dc89dc?q=80&w=772&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    products: getProductsByCategory('Hand Tools')
  },
  "Building Materials": {
    title: "Foundation to Finish.",
    image: "https://images.unsplash.com/photo-1593307315564-c96172dc89dc?q=80&w=772&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    products: getProductsByCategory('Building Materials')
  },
  "Safety Gear": {
    title: "Protect Yourself on Site.",
    image: "https://images.unsplash.com/photo-1593307315564-c96172dc89dc?q=80&w=772&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    products: getProductsByTag('safety-equipment')
  },
  "default": {
    title: "Hardware for Hard Work.",
    image: "https://images.unsplash.com/photo-1593307315564-c96172dc89dc?q=80&w=772&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    products: SYNCED_PRODUCTS
  }
};